name: Update JavaScript CLI branch

on:
  push:
    branches:
      - main-cli
  workflow_dispatch:

jobs:
  convert:
    uses: ./.github/workflows/convert-to-javascript.yml
    with:
      source-branch: main-cli
      target-branch: javascript-cli
