# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1a869f595aebb7c2b9b7cbf871fb5ee2"
name = "Eyesaloon Tryon"
application_url = "https://tryon-assets.eyesaloon.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "eyesaloon-wtps59lz.myshopify.com"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://tryon-assets.eyesaloon.com/api/auth" ]
